services:
  traefik:
    image: traefik:v3.4
    container_name: traefik

    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=your-email@example.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./infra/traefik:/letsencrypt

    restart: unless-stopped

  backend:
    image: ghcr.io/vszhyhalau/devops-platform-backend:latest

    env_file:
      - .env

    labels:
      - traefik.enable=true

      - traefik.http.routers.backend.rule=Host(`api.devops-platform.com`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=letsencrypt

      - traefik.http.services.backend.loadbalancer.server.port=8000

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    restart: unless-stopped

  postgres:
    image: postgres:16

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

  redis:
    image: redis:7

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

volumes:
  postgres_data:
