services:
  prometheus:
    image: prom/prometheus:v3.4.2

    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
      - "9090:9090"

    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.0.0

    labels:
      - traefik.enable=true

      - traefik.http.routers.grafana.rule=Host(`grafana.vzhyhalau-devops.uk`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt

      - traefik.http.services.grafana.loadbalancer.server.port=3000

    volumes:
      - grafana_data:/var/lib/grafana

    restart: unless-stopped

  traefik:
    image: traefik:v3.4
    container_name: traefik

    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=vasili.zhyhalau@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json

    labels:
      - traefik.enable=true

      - traefik.http.routers.traefik.rule=Host(`traefik.vzhyhalau-devops.uk`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt

      - traefik.http.routers.traefik.service=api@internal

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./infra/traefik:/letsencrypt

    restart: unless-stopped

  backend:
    image: ghcr.io/vszhigalov/devops-platform-backend:latest

    env_file:
      - .env

    labels:
      - traefik.enable=true

      - traefik.http.routers.backend.rule=Host(`api.vzhyhalau-devops.uk`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=letsencrypt

      - traefik.http.services.backend.loadbalancer.server.port=8000

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    restart: unless-stopped

  postgres:
    image: postgres:16

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

  redis:
    image: redis:7

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

volumes:
  postgres_data:
  grafana_data:
