name: Backend CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    backend-ci:
        runs-on: ubuntu-latest

        env:
            FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.12"

            - name: Install dependencies
              working-directory: ./backend
              run: |
                  pip install -r requirements.txt

            - name: Run syntax check
              working-directory: ./backend
              run: |
                  python -m compileall app

            - name: Build Docker image
              run: |
                  docker build -t devops-platform-backend ./backend
